import { splitLines} from './tools';
import {burst, countInfectingBursts, Direction, DirectionKey, Infection, parseGrid, turn} from './22';
import {range} from 'lodash';


const EXAMPLE: ReadonlyArray<string> = splitLines(`
..#
#..
...
`);

const EXAMPLE_BIG: ReadonlyArray<string> = splitLines(`
.........
.........
.........
.....#...
...#.....
.........
.........
.........
.........
`);

const ONE: ReadonlyArray<string> = splitLines(`
.........
.........
.........
.....#...
...##....
.........
.........
.........
.........
`);

const TWO: ReadonlyArray<string> = splitLines(`
.........
.........
.........
.....#...
...=#....
.........
.........
.........
.........
`);

const EXAMPLE_2: ReadonlyArray<string> = splitLines(`
#...#
.....
.....
.....
#...#
`);

const SEVEN: ReadonlyArray<string> = splitLines(`
.........
.........
.........
..#=.#...
..###....
.........
.........
.........
.........
`);

describe('day 22', () => {
  describe('turn()', () => {
    [
      ['left', true, 'down'],
      ['down', true, 'right'],
      ['right', true, 'up'],
      ['up', true, 'left'],

      ['left', false, 'up'],
      ['up', false, 'right'],
      ['right', false, 'down'],
      ['down', false, 'left'],
    ].forEach(([dir, left, next]: [DirectionKey, boolean, DirectionKey]) => {
      it(`should turn ${left ? 'left': 'right'} from ${dir} to ${next}`, () => {
        expect(turn(Direction[dir], left)).toEqual(Direction[next]);
      });
    });
  });

  describe('parseGrid()', () => {
    it('should work for example', () => {
      expect(parseGrid(EXAMPLE)).toEqual({'-1,0': true,'1,-1': true})
    });
    it('should work for example 2', () => {
      expect(parseGrid(EXAMPLE_2)).toEqual({'-2,-2': true,'2,-2': true,'2,2': true,'-2,2': true})
    });
    it('should work for example with false', () => {
      expect(parseGrid(TWO)).toEqual({'0,0': true,'1,-1': true,'-1,0': false})
    });
    it('should work for small and big example', () => {
      expect(parseGrid(EXAMPLE)).toEqual(parseGrid(EXAMPLE_BIG))
    });
  });

  describe('burst()', () => {
    it('should work for example', () => {
      const initial = parseGrid(EXAMPLE);
      const infection: Infection = {
        grid: initial,
        position: [0,0],
        direction: Direction.up
      };
      const steps: Infection[] = [burst(infection)];
      range(1,7).forEach(i => steps.push(burst(steps[i - 1])));
      const [first, second, third, fourth, fifth, sixth, seventh] = steps;
      expect(first).toEqual({grid: parseGrid(ONE), position: [-1,0], direction: Direction.left});
      expect(second).toEqual({grid: parseGrid(TWO), position: [-1,-1], direction: Direction.up});
      expect(seventh.grid).toEqual(parseGrid(SEVEN));
    });
  });

  describe('countInfectingBursts()', () => {
    [
      [7, 5],
      [70, 41],
      [10000, 5587],
    ].forEach(([iterations, expected]: [number, number]) => {
      it(`${iterations} iterations should cause ${expected} infections`, () => {
        expect(countInfectingBursts(parseGrid(EXAMPLE), iterations)).toBe(expected)
      });
    });
  });
});
